"""
Django settings for CyberCP project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import json
import os
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
# Important: under systemd/lswsgi the working directory is not guaranteed,
# so we must load `.env` from the project root explicitly.
try:
    from dotenv import load_dotenv

    load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env'))
except ImportError:
    # dotenv not available, continue without it
    pass

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _read_mysql_password_file():
    """
    CyberPanel stores MySQL credentials in /etc/cyberpanel/mysqlPassword.
    Same file phpMyAdmin / install scripts use. Format is either:
    - Plain text: first line = root password (legacy)
    - JSON: mysqluser, mysqlpassword, mysqlhost, mysqlport (remote or structured installs)

    Django defaults DB_PASSWORD from env; if empty (common when .env is missing or not
    loaded under lswsgi), fall back to this file so the panel does not connect with
    "using password: NO" while phpMyAdmin still works via the file.
    """
    path = '/etc/cyberpanel/mysqlPassword'
    if not os.path.isfile(path):
        return None, None, None
    try:
        raw = open(path, 'r').read().strip()
        if raw.startswith('{'):
            data = json.loads(raw)
            pw = data.get('mysqlpassword') or data.get('password')
            host = data.get('mysqlhost')
            port = data.get('mysqlport')
            return pw, host, str(port) if port is not None else None
        line = raw.split('\n', 1)[0].strip('\r\n')
        return line, None, None
    except Exception:
        return None, None, None


_FILE_PW, _FILE_HOST, _FILE_PORT = _read_mysql_password_file()

# Resolve DB_* / ROOT_DB_* with file fallback when env left empty
_DB_NAME = os.getenv('DB_NAME', 'cyberpanel')
_DB_USER = os.getenv('DB_USER', 'cyberpanel')
_DB_PASS = os.getenv('DB_PASSWORD', '') or ''
if not _DB_PASS and _FILE_PW:
    _DB_PASS = _FILE_PW

_DB_HOST = os.getenv('DB_HOST', '127.0.0.1')
if 'DB_HOST' not in os.environ and _FILE_HOST:
    _DB_HOST = _FILE_HOST

_DB_PORT = os.getenv('DB_PORT', '3306')
if 'DB_PORT' not in os.environ and _FILE_PORT:
    _DB_PORT = _FILE_PORT

_ROOT_DB_NAME = os.getenv('ROOT_DB_NAME', 'mysql')
_ROOT_DB_USER = os.getenv('ROOT_DB_USER', 'root')
_ROOT_DB_PASS = os.getenv('ROOT_DB_PASSWORD', '') or ''
if not _ROOT_DB_PASS and _FILE_PW:
    _ROOT_DB_PASS = _FILE_PW

_ROOT_DB_HOST = os.getenv('ROOT_DB_HOST', '127.0.0.1')
if 'ROOT_DB_HOST' not in os.environ and _FILE_HOST:
    _ROOT_DB_HOST = _FILE_HOST

_ROOT_DB_PORT = os.getenv('ROOT_DB_PORT', '3306')
if 'ROOT_DB_PORT' not in os.environ and _FILE_PORT:
    _ROOT_DB_PORT = _FILE_PORT

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'xr%j*p!*$0d%(-(e%@-*hyoz4$f%y77coq0u)6pwmjg4)q&19f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Allow configuration via environment variable, with wildcard fallback for universal compatibility
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'baseTemplate',
    'firewall',
    'loginSystem',
    'packages',
    'websiteFunctions',
    'tuning',
    'serverStatus',
    'dns',
    'ftp',
    'userManagment',
    'databases',
    'mailServer',
    'serverLogs',
    'backup',
    'managePHP',
    'manageSSL',
    'api',
    'filemanager',
    'manageServices',
    'pluginHolder',
    'emailPremium',
    'emailMarketing',
    'cloudAPI',
    'highAvailability',
    's3Backups',
    'dockerManager',
    'containerization',
    'CLManager',
    'IncBackups',
    'aiScanner',
    'webmail',
    'emailDelivery',
    #    'WebTerminal'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CyberCP.secMiddleware.secMiddleware'

]

ROOT_URLCONF = 'CyberCP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'baseTemplate.context_processors.version_context',
                'baseTemplate.context_processors.cosmetic_context',

            ],
        },
    },
]

WSGI_APPLICATION = 'CyberCP.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _DB_NAME,
        'USER': _DB_USER,
        'PASSWORD': _DB_PASS,
        'HOST': _DB_HOST,
        'PORT': _DB_PORT,
    },
    'rootdb': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': _ROOT_DB_NAME,
        'USER': _ROOT_DB_USER,
        'PASSWORD': _ROOT_DB_PASS,
        'HOST': _ROOT_DB_HOST,
        'PORT': _ROOT_DB_PORT,
    },
}
DATABASE_ROUTERS = ['backup.backupRouter.backupRouter']

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

STATIC_URL = '/static/'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = (
    ('en', _('English')),
    ('cn', _('Chinese')),
    ('br', _('Bulgarian')),
    ('pt', _('Portuguese')),
    ('ja', _('Japanese')),
    ('bs', _('Bosnian')),
    ('gr', _('Greek')),
    ('ru', _('Russian')),
    ('tr', _('Turkish')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('pl', _('Polish')),
    ('vi', _('Vietnamese')),
    ('it', _('Italian')),
    ('de', _('Deutsch')),
    ('id', _('Indonesian')),
    ('bn', _('Bangla')),
    ('nb', _('Norwegian Bokmål')),
)

MEDIA_URL = '/usr/local/CyberCP/tmp/'
MEDIA_ROOT = MEDIA_URL
DATA_UPLOAD_MAX_MEMORY_SIZE = 2147483648

# Security settings
X_FRAME_OPTIONS = 'SAMEORIGIN'