# Generated by Django 4.2.14 on 2026-03-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberMailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_account_id', models.IntegerField(null=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('plan_name', models.CharField(default='Free', max_length=100)),
                ('plan_slug', models.CharField(default='free', max_length=50)),
                ('emails_per_month', models.IntegerField(default=15000)),
                ('is_connected', models.BooleanField(default=False)),
                ('relay_enabled', models.BooleanField(default=False)),
                ('smtp_credential_id', models.IntegerField(null=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_host', models.CharField(default='mail.cyberpersons.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cybermail_account', to='loginSystem.administrator')),
            ],
            options={
                'db_table': 'cybermail_accounts',
            },
        ),
        migrations.CreateModel(
            name='CyberMailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('platform_domain_id', models.IntegerField(null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('spf_verified', models.BooleanField(default=False)),
                ('dkim_verified', models.BooleanField(default=False)),
                ('dmarc_verified', models.BooleanField(default=False)),
                ('dns_configured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='emailDelivery.cybermailaccount')),
            ],
            options={
                'db_table': 'cybermail_domains',
            },
        ),
    ]
