# Generated by Django 4.2.14 on 2026-03-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=50, unique=True)),
                ('diskSpace', models.IntegerField()),
                ('bandwidth', models.IntegerField()),
                ('emailAccounts', models.IntegerField(null=True)),
                ('dataBases', models.IntegerField(default=0)),
                ('ftpAccounts', models.IntegerField(default=0)),
                ('allowedDomains', models.IntegerField(default=0)),
                ('allowFullDomain', models.IntegerField(default=1)),
                ('enforceDiskLimits', models.IntegerField(default=0)),
                ('memoryLimitMB', models.IntegerField(default=1024, help_text='Memory limit in MB')),
                ('cpuCores', models.IntegerField(default=1, help_text='Number of CPU cores')),
                ('ioLimitMBPS', models.IntegerField(default=10, help_text='I/O limit in MB/s')),
                ('inodeLimit', models.IntegerField(default=400000, help_text='Maximum number of files/directories')),
                ('maxConnections', models.IntegerField(default=10, help_text='Max concurrent PHP connections')),
                ('procSoftLimit', models.IntegerField(default=400, help_text='Soft process limit')),
                ('procHardLimit', models.IntegerField(default=500, help_text='Hard process limit')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.administrator')),
            ],
        ),
    ]
