# Generated by Django 4.2.14 on 2026-03-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('websiteFunctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailServerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_addressing_enabled', models.BooleanField(default=False)),
                ('plus_addressing_delimiter', models.CharField(default='+', max_length=1)),
            ],
            options={
                'db_table': 'e_server_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatternForwarding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('pattern_type', models.CharField(choices=[('wildcard', 'Wildcard'), ('regex', 'Regular Expression')], default='wildcard', max_length=20)),
                ('priority', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'e_pattern_forwarding',
                'ordering': ['priority'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domain', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('childOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.childdomains')),
                ('domainOwner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='websiteFunctions.websites')),
            ],
            options={
                'db_table': 'e_domains',
            },
        ),
        migrations.CreateModel(
            name='Forwardings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('destination', models.TextField()),
            ],
            options={
                'db_table': 'e_forwardings',
            },
        ),
        migrations.CreateModel(
            name='Pipeprograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('destination', models.TextField()),
            ],
            options={
                'db_table': 'e_pipeprograms',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128, unique=True)),
                ('transport', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'e_transport',
            },
        ),
        migrations.CreateModel(
            name='CatchAllEmail',
            fields=[
                ('domain', models.OneToOneField(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mailServer.domains')),
                ('destination', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'e_catchall',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlusAddressingOverride',
            fields=[
                ('domain', models.OneToOneField(db_column='domain_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mailServer.domains')),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'e_plus_override',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EUsers',
            fields=[
                ('email', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=200)),
                ('mail', models.CharField(default='', max_length=200)),
                ('DiskUsage', models.CharField(default='0', max_length=200)),
                ('emailOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailServer.domains')),
            ],
            options={
                'db_table': 'e_users',
            },
        ),
    ]
